### ISSUE TITLE
Whitespace control isn't works

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#159] opened 2016-10-05 10:40 UTC
[Whitespace controll](https://help.shopify.com/themes/liquid/basics/whitespace)

Template: 

```
{%- include 'parameters' -%}
```

``````
Creating code files...
liquid-3.0.6/lib/liquid/block.rb:41:in `parse': Liquid syntax error: Tag '{%- include 'parameters' -%}' was not properly terminated with regexp: /\%\}/ (Liquid::SyntaxError)
    from liquid-3.0.6/lib/liquid/tag.rb:10:in `parse'
    from liquid-3.0.6/lib/liquid/document.rb:5:in `parse'
    from liquid-3.0.6/lib/liquid/template.rb:122:in `parse'
    from liquid-3.0.6/lib/liquid/template.rb:108:in `parse'
    from generamba-1.2.2/lib/generamba/code_generation/content_generator.rb:18:in `create_file'
    from generamba-1.2.2/lib/generamba/module_generator.rb:79:in `block in process_files_if_needed'
    from generamba-1.2.2/lib/generamba/module_generator.rb:62:in `each'
    from generamba-1.2.2/lib/generamba/module_generator.rb:62:in `process_files_if_needed'
    from generamba-1.2.2/lib/generamba/module_generator.rb:22:in `generate_module'
    from generamba-1.2.2/lib/generamba/cli/gen_command.rb:72:in `gen'
    from thor-0.19.1/lib/thor/command.rb:27:in `run'
    from thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from thor-0.19.1/lib/thor/base.rb:440:in `start'
    from generamba-1.2.2/bin/generamba:5:in `<top (required)>'
    from /Users/maksim.bazarov/.rbenv/versions/2.3.1/bin/generamba:23:in `load'
    from /Users/maksim.bazarov/.rbenv/versions/2.3.1/bin/generamba:23:in `<main>'```
``````

**Comment by MaximBazarov** [comment] 2016-10-06 10:48
might be more informative 

```
block.rb:41:in `parse': Liquid syntax error: Tag '{%- include 'parameters' -%}' was not properly terminated with regexp: /\%\}/ (Liquid::SyntaxError)
```

**Comment by MaximBazarov** [comment] 2016-10-06 11:04
and 

```
{% include 'parameters' -%}' 
```

works fine

**Comment by etolstoy** [comment] 2016-10-07 06:23
@MaksimBazarov looks like the problem is in [liquid gem](https://github.com/Shopify/liquid)^ your tag doesn't pass their built-in regexp. Try to post the issue in their tracker.

**Comment by MaximBazarov** [comment] 2016-10-07 20:58
Whitespace control tags were added in Liquid 4 and are not available in version 3.
https://github.com/Shopify/liquid/issues/807#issuecomment-252236338

@etolstoy could you please update the liquid gem?

**Comment by etolstoy** [comment] 2016-10-08 10:47
Version 4 is [not stable yet](https://github.com/Shopify/liquid/blob/master/History.md), so I'd better wait for its release.

**Comment by etolstoy** [comment] 2016-11-08 13:06
As @fw42 says in [this issue](https://github.com/Shopify/liquid/issues/818), the 4.0 version will be released really soon.

Closing this issue and creating new one (#167).

**Closed as completed by etolstoy** 2016-11-08 13:06 UTC
Labels: bug
